name: tuba
base: core22
version: git
adopt-info: tuba

grade: devel
confinement: strict
license: GPL-3.0-only
compression: lzo

slots:
  tuba:
    interface: dbus
    bus: session
    name: dev.geopjr.Tuba

apps:
  tuba:
    command: usr/bin/dev.geopjr.Tuba
    desktop: usr/share/applications/dev.geopjr.Tuba.desktop
    common-id: dev.geopjr.Tuba.desktop
    extensions: [gnome]
    plugs:
      - network-status
      - network

parts:
  tuba:
    source: .
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Ddevel=true
    parse-info: [usr/share/metainfo/dev.geopjr.Tuba.metainfo.xml]
    build-environment:
      - CC: "clang"
    build-packages:
      - clang
      - libjson-glib-dev
      - libsecret-1-dev
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - tuba
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gnome-42-2204-sdk
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gnome-42-2204-sdk"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
