on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: macOS
jobs:
  macos:
    strategy:
      matrix:
        runner: [macos-latest, macos-13]
        include:
          - runner: macos-latest
            arch: arm64
          - runner: macos-13
            arch: x86-64
    name: macOS (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: brew bundle
        continue-on-error: true
      - name: Make
        run: brew bundle exec -- make macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuba_macos_${{ matrix.arch }}
          path: tuba_macos.dmg
          if-no-files-found: error
