on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: macOS
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: brew bundle
        continue-on-error: true
      - name: Make
        run: brew bundle exec -- make macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuba_macos
          path: tuba_macos.dmg
          if-no-files-found: error
