on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: macOS
jobs:
  macos:
    strategy:
      matrix:
        runner: [macos-latest, macos-13]
        include:
          - runner: macos-latest
            arch: arm64
          - runner: macos-13
            arch: x86-64
    name: macOS (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: brew bundle
        continue-on-error: true
      - name: Make
        run: brew bundle exec -- make macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuba_macos_${{ matrix.arch }}
          path: tuba_macos.dmg
          if-no-files-found: error
  macos-universal:
    name: macOS (universal)
    needs: macos
    runs-on: macos-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Attach DMGs
        run: |
          hdiutil attach tuba_macos_x86-64/tuba_macos.dmg # /Volumes/tuba_macos
          hdiutil attach tuba_macos_arm64/tuba_macos.dmg # /Volumes/tuba_macos 1
      - name: Duplicate x86-64 app
        run: |
          mkdir tuba_macos_universal
          cp /Volumes/tuba_macos/* tuba_macos_universal
          rm tuba_macos_universal/Tuba.app/Contents/MacOS/dev.geopjr.Tuba
      - name: Create Universal Binary
        run: |
          lipo \
            "/Volumes/tuba_macos/Tuba.app/Contents/MacOS/dev.geopjr.Tuba" \
            "/Volumes/tuba_macos 1/Tuba.app/Contents/MacOS/dev.geopjr.Tuba" \
            -create \
            -output "tuba_macos_universal/Tuba.app/Contents/MacOS/dev.geopjr.Tuba"
      - name: Create DMG for universal app
        run: hdiutil create -srcfolder tuba_macos_universal tuba_macos_universal.dmg
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuba_macos_universal
          path: tuba_macos_universal.dmg
          if-no-files-found: error
